package coffeeshop;


import Employee.EmployeeDashboard;
import admin.U_Admin;
import admin.adminDashboard;
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Coffeeshop extends javax.swing.JFrame {

  
    public Coffeeshop() {
        initComponents();
        this.setResizable(false);
    }
    
    static String status;
    static String type;
    public static boolean logAcc(String username, String password, String email)
    {
        dbConnect connector = new dbConnect();
        try
        {
            String query = "SELECT * FROM tbl_accounts WHERE u_username='"+ username +"'AND u_pass='"+ password +"'AND u_email='"+ email +"'";
            ResultSet resultSet = connector.getData(query);
            if(resultSet.next())
            {
                status = resultSet.getString("u_status");
                type = resultSet.getString("u_accType");
                return true;
            }else
            {
                return false;
            }
        }catch(SQLException ex)
        {
            return false;
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manager_Login1 = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Navigation1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Mpassword = new javax.swing.JPasswordField();
        MR_clickhere = new javax.swing.JLabel();
        Musername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Memail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        register1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Manager_Login1.setBackground(new java.awt.Color(153, 153, 153));
        Manager_Login1.setForeground(new java.awt.Color(204, 204, 204));
        Manager_Login1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header1.setBackground(new java.awt.Color(51, 51, 51));
        Header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 255, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COFFEE SHOP");
        Header1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 690, 40));

        Manager_Login1.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 690, 100));

        Navigation1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Navigation1Layout = new javax.swing.GroupLayout(Navigation1);
        Navigation1.setLayout(Navigation1Layout);
        Navigation1Layout.setHorizontalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        Navigation1Layout.setVerticalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        Manager_Login1.add(Navigation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Login");
        Manager_Login1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 160, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("PASSWORD:");
        Manager_Login1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 100, 30));

        Mpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpasswordActionPerformed(evt);
            }
        });
        Manager_Login1.add(Mpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 330, 30));

        MR_clickhere.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MR_clickhere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MR_clickhere.setText("Add new owner account? click here");
        MR_clickhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MR_clickhereMouseClicked(evt);
            }
        });
        Manager_Login1.add(MR_clickhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 330, 20));

        Musername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Musername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusernameActionPerformed(evt);
            }
        });
        Manager_Login1.add(Musername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 330, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("EMAIL:");
        Manager_Login1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 70, 30));

        Memail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Memail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemailActionPerformed(evt);
            }
        });
        Manager_Login1.add(Memail, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 330, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("USERNAME:");
        Manager_Login1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 90, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Manager_Login1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 160, 30));

        register1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register1.setText("LOGIN");
        register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register1MouseClicked(evt);
            }
        });
        Manager_Login1.add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Manager_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Manager_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MpasswordActionPerformed

    private void MR_clickhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MR_clickhereMouseClicked
        Registration r = new Registration();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MR_clickhereMouseClicked

    private void MusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusernameActionPerformed

    private void MemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemailActionPerformed

    private void register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register1MouseClicked
        String uname = Musername.getText().trim();
        String e = Memail.getText().trim();
        String pass = new String(Mpassword.getPassword()).trim();
    
        if(logAcc(uname,pass,e))
        {
            if(!status.equals("Active")  )
            {
                JOptionPane.showMessageDialog(null, "Inactive Account, Contact Admin");
            }else
            {
                if(type.equals("Admin"))
                {
                    JOptionPane.showMessageDialog(null, "Login Succesfully");
                    adminDashboard ad = new adminDashboard();
                    ad.setVisible(true);
                    this.dispose();
                }
                if(type.equals("Employee"))
                {
                    JOptionPane.showMessageDialog(null, "Login Succesfully");
                    EmployeeDashboard ed = new EmployeeDashboard();
                    ed.setVisible(true);
                    this.dispose();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Unknown Account Type, Contact the Admin");
                }
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Invalid Account");
        }
    }//GEN-LAST:event_register1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffeeshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header1;
    private javax.swing.JLabel MR_clickhere;
    private javax.swing.JPanel Manager_Login1;
    private javax.swing.JTextField Memail;
    private javax.swing.JPasswordField Mpassword;
    private javax.swing.JTextField Musername;
    private javax.swing.JPanel Navigation1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton register1;
    // End of variables declaration//GEN-END:variables
}
