package Startups;


import Employee.EmployeeDashboard;
import admin.U_Admin;
import admin.adminDashboard;
import config.Session;
import config.dbConnect;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Coffeeshop extends javax.swing.JFrame {

  
    public Coffeeshop() {
        initComponents();
        this.setResizable(false);
    }
    
    static String status;
    static String type;
    public static boolean logAcc(String username, String password)
    {
        dbConnect connector = new dbConnect();
        try
        {
            String query = "SELECT * FROM tbl_accounts WHERE u_username='"+ username +"'";
            ResultSet resultSet = connector.getData(query);
            if(resultSet.next())
            {
                String hashedPass = resultSet.getString("u_pass");
                String rehashedPass = passwordHasher.hashPassword(password);

                if(hashedPass.equals(rehashedPass))
                {
            
                status = resultSet.getString("u_status");
                type = resultSet.getString("u_accType");
                
                Session sess = Session.getInstance();
                sess.setUid(resultSet.getInt("u_id"));
                sess.setUname(resultSet.getString("u_username"));
                sess.setType(resultSet.getString("u_accType"));
                sess.setMail(resultSet.getString("u_email"));
                return true;
                }else
                {
                    return false;
                }
            }else
            {
                return false;
            }
        }catch(SQLException | NoSuchAlgorithmException ex)
        {
            System.out.println(""+ex); // Always put 
            return false;
        }
    } ///llllllll
    
    
    
    
    public void logEvent(int userId, String username, String action) {
        dbConnect dbc = new dbConnect();
        Connection con = dbc.getConnection();
        PreparedStatement pstmt = null;
        Timestamp time = new Timestamp(new Date().getTime());
        System.out.println("userId: "+userId);

        try {
            String sql = "INSERT INTO tbl_logs (u_id, u_username, action_time, log_action) "
                    + "VALUES ('" + userId + "', '" + username + "', '" + time + "', '" + action + "')";
            pstmt = con.prepareStatement(sql);

            /*            pstmt.setInt(1, userId);
            pstmt.setString(2, username);
            pstmt.setTimestamp(3, new Timestamp(new Date().getTime()));
            pstmt.setString(4, userType);*/
            pstmt.executeUpdate();
            System.out.println("Login log recorded successfully.");
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, "Error recording log: " + e.getMessage());
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error closing resources: " + e.getMessage());
            }
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manager_Login1 = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Navigation1 = new javax.swing.JPanel();
        logo_jpg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Mpassword = new javax.swing.JPasswordField();
        MR_clickhere = new javax.swing.JLabel();
        Musername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        register1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        register2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Manager_Login1.setBackground(new java.awt.Color(176, 136, 109));
        Manager_Login1.setForeground(new java.awt.Color(204, 204, 204));
        Manager_Login1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header1.setBackground(new java.awt.Color(51, 51, 51));
        Header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 255, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COFFEE SHOP");
        Header1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 30, 690, 40));

        Manager_Login1.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 620, 100));

        Navigation1.setBackground(new java.awt.Color(215, 209, 191));
        Navigation1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_jpg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N
        Navigation1.add(logo_jpg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -10, 960, 640));

        Manager_Login1.add(Navigation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 680));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Login");
        Manager_Login1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 160, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("PASSWORD:");
        Manager_Login1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 100, 30));

        Mpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpasswordActionPerformed(evt);
            }
        });
        Manager_Login1.add(Mpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 330, 30));

        MR_clickhere.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MR_clickhere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MR_clickhere.setText("Forgot Pass? click here");
        MR_clickhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MR_clickhereMouseClicked(evt);
            }
        });
        Manager_Login1.add(MR_clickhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 330, 20));

        Musername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Musername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusernameActionPerformed(evt);
            }
        });
        Manager_Login1.add(Musername, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 330, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("USERNAME:");
        Manager_Login1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 90, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Manager_Login1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 160, 30));

        register1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register1.setText("LOGIN");
        register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register1MouseClicked(evt);
            }
        });
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });
        Manager_Login1.add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 390, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cup.png"))); // NOI18N
        Manager_Login1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 480, 250));

        check1.setBackground(new java.awt.Color(176, 136, 109));
        check1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        check1.setText("Show");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        Manager_Login1.add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, -1, -1));

        register2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register2.setText("Register");
        register2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register2MouseClicked(evt);
            }
        });
        register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register2ActionPerformed(evt);
            }
        });
        Manager_Login1.add(register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Manager_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manager_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MpasswordActionPerformed

    private void MR_clickhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MR_clickhereMouseClicked
        ForgetPass fp = new ForgetPass();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MR_clickhereMouseClicked

    private void MusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusernameActionPerformed

    private void register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register1MouseClicked
        Session sess = Session.getInstance();
        dbConnect connector = new dbConnect();
        String uname = Musername.getText().trim();
        String pass = new String(Mpassword.getPassword()).trim();
        int userId = sess.getUid();
        System.out.println(""+userId);
    
        if(pass.isEmpty() || uname.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill all Boxes");
        }else if(logAcc(uname,pass))
        {
            if(!status.equals("Active")  )
            {
                JOptionPane.showMessageDialog(null, "Inactive Account, Contact Admin");
            }else
            {
                
                try {
                    String query = "SELECT u_id FROM tbl_accounts WHERE u_username = '" + uname + "'";
                    PreparedStatement pstmt = connector.getConnection().prepareStatement(query);

                    ResultSet resultSet = pstmt.executeQuery();

                    if (resultSet.next()) {
                        userId = resultSet.getInt("u_id");   // Update the outer `userId` correctly
                    }
                } catch (SQLException ex) {
                    System.out.println("SQL Exception: " + ex);
                }
                
                
                if(type.equals("Admin"))
                {
                    logEvent(userId, uname, "Logged as Admin");
                    JOptionPane.showMessageDialog(null, "Login Succesfully");
                    adminDashboard ad = new adminDashboard();
                    ad.setVisible(true);
                    this.dispose();
                }
                else if(type.equals("Employee"))
                {
                    logEvent(userId, uname, "Logged as Employee");
                    JOptionPane.showMessageDialog(null, "Login Succesfully");
                    EmployeeDashboard ed = new EmployeeDashboard();
                    ed.setVisible(true);
                    this.dispose();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Unknown Account Type, Contact the Admin");
                }
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Invalid Account");
        }
    }//GEN-LAST:event_register1MouseClicked

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        boolean isSelected = check1.isSelected();

        if (isSelected) {
            Mpassword.setEchoChar((char)0);
        } else {
            Mpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register1ActionPerformed

    private void register2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_register2MouseClicked

    private void register2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register2ActionPerformed
        Registration r = new Registration();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_register2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffeeshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header1;
    private javax.swing.JLabel MR_clickhere;
    private javax.swing.JPanel Manager_Login1;
    private javax.swing.JPasswordField Mpassword;
    private javax.swing.JTextField Musername;
    private javax.swing.JPanel Navigation1;
    private javax.swing.JCheckBox check1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_jpg;
    private javax.swing.JButton register1;
    private javax.swing.JButton register2;
    // End of variables declaration//GEN-END:variables
}
